Document: gr-foo
Title: Debian gr-foo Manual
Author: <insert document author here>
Abstract: This manual describes what gr-foo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gr-foo/gr-foo.sgml.gz

Format: postscript
Files: /usr/share/doc/gr-foo/gr-foo.ps.gz

Format: text
Files: /usr/share/doc/gr-foo/gr-foo.text.gz

Format: HTML
Index: /usr/share/doc/gr-foo/html/index.html
Files: /usr/share/doc/gr-foo/html/*.html
